### ISSUE TITLE
Want it so bad!

### ISSUE THREAD

**Issue by j2l** [Starfall-Robles/Blender-2-G-MIC#5]
I tried with 2.79 and 2.81, menu not showing.
I registered G'MIC-cli-win64 path before opening blender, it starts in powershell.

Any chance to adapt it to 2.8+?

**Comment by myselfhimself** [comment]
We are a different team working on it in a different implementation, it will take time, maybe a few months: see here: https://github.com/myselfhimself/gmic-blender

**Comment by j2l** [comment]
Cool!
Starred and watched.
